using System;
using System.Text.Json.Nodes;

namespace UndertaleModToolAvalonia.Android.Api;

/// <summary>
/// Wire-level constants of the cross-app API: the names a client app has to know without taking a
/// dependency on this APK. They must stay in sync with <c>Api/IUmApi.aidl</c> (the descriptor is
/// what a client's generated AIDL stub checks) and with <c>Properties/AndroidManifest.xml</c>
/// (the permission).
/// </summary>
public static class UmApiContract
{
    /// <summary>The app's application id (<c>ApplicationId</c> in the .csproj).</summary>
    public const string PackageName = "com.undertalemodtool.avalonia.android";

    /// <summary>
    /// Signature-or-user-granted permission a client must declare (see
    /// <c>Properties/AndroidManifest.xml</c>) before the system lets it bind the API service.
    /// </summary>
    public const string Permission = PackageName + ".permission.RUN_SCRIPT";

    /// <summary>
    /// Action of the intent a client binds with. The service's Java class name is generated by the
    /// .NET Android build (a <c>crc64...</c> name), so clients should either bind with this action
    /// (<c>PackageManager.QueryIntentServices</c> / <c>bindService</c> with the action) or read
    /// <c>serviceComponent</c> from <c>getApiInfo</c>.
    /// </summary>
    public const string BindAction = PackageName + ".api.action.BIND_UM_API";

    /// <summary>
    /// Version of the API surface itself (not of the app): bumped when methods or JSON fields
    /// change in a way clients have to know about.
    /// </summary>
    public const string ApiVersion = "1";

    /// <summary>AIDL package + interface name, i.e. the descriptor both sides embed in the parcel.</summary>
    public const string Descriptor = PackageName + ".api.IUmApi";

    /// <summary>Largest script text accepted by <c>startScriptText</c> (Binder caps a transaction at 1 MB).</summary>
    public const int MaxScriptTextLength = 512 * 1024;

    /// <summary>Largest chunk <c>getJobOutput</c> returns in one call.</summary>
    public const int MaxOutputChunkLength = 64 * 1024;

    /// <summary>Upper bound for the per-job captured log; further output is replaced by a notice.</summary>
    public const int MaxJobOutputLength = 8 * 1024 * 1024;

    /// <summary>Upper bound for the last SetUMTConsoleText value returned by <c>getJob</c>.</summary>
    public const int MaxConsoleTextLength = 64 * 1024;
}

/// <summary>
/// Small helpers for the hand-rolled JSON documents the API returns. <see cref="JsonNode"/> based
/// so nothing depends on reflection-based serialization (which trimming could break).
/// </summary>
internal static class UmApiJson
{
    public static string Write(JsonObject o) => o.ToJsonString();

    public static JsonObject Ok() => new() { ["ok"] = true };

    public static JsonObject Failure(string error, JsonObject? target = null)
    {
        JsonObject o = target ?? new JsonObject();
        o["ok"] = false;
        o["error"] = error;
        return o;
    }

    public static JsonObject Object(params (string Key, JsonNode? Value)[] members)
    {
        JsonObject o = new();
        foreach ((string key, JsonNode? value) in members)
        {
            o[key] = value;
        }
        return o;
    }

    public static JsonArray Array(params JsonNode?[] items)
    {
        JsonArray a = new();
        foreach (JsonNode? item in items)
        {
            a.Add(item);
        }
        return a;
    }

    /// <summary>Reads a per-job "optionsJson" argument without throwing on malformed input.</summary>
    public static bool ReadBool(string? json, string key, bool fallback)
    {
        if (string.IsNullOrWhiteSpace(json))
            return fallback;

        try
        {
            JsonNode? node = JsonNode.Parse(json);
            if (node is JsonObject o && o.TryGetPropertyValue(key, out JsonNode? value) && value is not null)
            {
                return value.GetValueKind() switch
                {
                    System.Text.Json.JsonValueKind.True => true,
                    System.Text.Json.JsonValueKind.False => false,
                    _ => fallback,
                };
            }
        }
        catch (Exception)
        {
            // Malformed options are ignored; defaults apply.
        }

        return fallback;
    }
}
