using System;
using Android.App;
using Android.Content;
using Android.Content.PM;
using Android.OS;

namespace UndertaleModToolAvalonia.Android.Api;

/// <summary>
/// The exported, permission-protected entry point of the cross-app API: a bound service that
/// returns the <see cref="UmApiBinder"/> implementing <c>IUmApi</c>.
/// <para>
/// The Java class name of this type is generated by the .NET Android build (a <c>crc64...</c>
/// name), so clients normally bind to it through <see cref="UmApiContract.BindAction"/> instead of
/// an explicit <c>ComponentName</c>. Because the service lives in the app's main process, binding
/// to it also starts that process - without any activity, which is what makes the API usable while
/// the tool is not on screen.
/// </para>
/// </summary>
[Service(
    Exported = true,
    Permission = UmApiContract.Permission,
    Label = "QiuUTMTv5 script API",
    // Emitted literally as android:description, which aapt2 requires to be a resource reference.
    Description = "@string/um_api_service_description")]
// The intent filter is fully qualified because Android.Content (for Context) and Android.App both
// declare an IntentFilter type, and only the latter is the attribute.
[global::Android.App.IntentFilter(new[] { UmApiContract.BindAction })]
public sealed class UmApiService : Service
{
    const string LogTag = "UmApi";

    /// <summary>
    /// Called on every <c>bindService</c>. The manifest permission already restricts who can get
    /// here, but the check is repeated so that a manifest merge, an <c>adb</c> call or a future
    /// <c>exported</c> change cannot silently open the scripting engine to any app.
    /// </summary>
    public override IBinder? OnBind(Intent? intent)
    {
        if (!UmApiSecurity.IsCallerAuthorized(this))
        {
            global::Android.Util.Log.Warn(LogTag, "Rejected a bind from uid " + Binder.CallingUid +
                                          " (missing " + UmApiContract.Permission + ")");
            return null;
        }

        global::Android.Util.Log.Info(LogTag, "Client bound to the script API (uid " + Binder.CallingUid + ")");
        return new UmApiBinder(this);
    }

    public override bool OnUnbind(Intent? intent)
    {
        global::Android.Util.Log.Info(LogTag, "Client unbound from the script API");
        return base.OnUnbind(intent);
    }
}

/// <summary>
/// Decides whether the caller of a Binder transaction may use the API.
/// </summary>
internal static class UmApiSecurity
{
    /// <summary>
    /// True for this app itself, for apps holding <see cref="UmApiContract.Permission"/> and for
    /// apps signed with the same certificate (the last one is what <c>signature|dangerous</c>
    /// actually grants - see Api/README.md).
    /// </summary>
    public static bool IsCallerAuthorized(Context context)
    {
        int callerUid = Binder.CallingUid;
        int ownUid = global::Android.OS.Process.MyUid();

        if (callerUid == ownUid)
            return true;

        try
        {
            if (context.CheckCallingPermission(UmApiContract.Permission) == Permission.Granted)
                return true;

            if (context.PackageManager?.CheckSignatures(callerUid, ownUid) == SignatureResult.Match)
                return true;
        }
        catch (Exception)
        {
            // CheckSignatures can throw for uids that have no packages (isolated processes); an
            // exception means "not provably authorized", which is a denial.
        }

        return false;
    }
}
